[tool.poetry]
name = "test-desuyo"
version = "0.1.0"
description = ""
authors = ["'Yuji.K' <'yujikagsigkomi@gmail.com'>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
polars = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
